name: Lint

on:
  push:
    branches:
      - "feat/**"
      - "refactor/**"
      - "fix/**"
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_call:

permissions: write-all

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: ["1.23.0"]

    steps:
      - uses: Kesin11/actions-timeline@v2

      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.goversion }}
          cache: true
          cache-dependency-path: go.sum

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Setup staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: staticcheck with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          staticcheck ./... | reviewdog -f=staticcheck -reporter=github-pr-check -level warning